name: who_called_me
description: >-
  Get info on which function called a function, including line number, path et al, packaged into a handy class structure for easy access.
version: 0.0.1
repository: https://github.com/stobix/dart_caller

environment:
  sdk: '>=2.17.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
